// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: net/ActCustomGift.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "net/ActCustomGift.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace pb {

namespace {

const ::google::protobuf::Descriptor* TActCustomGiftInfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TActCustomGiftInfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* TActCustomGiftGetInfoArrRsp_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TActCustomGiftGetInfoArrRsp_reflection_ = NULL;
const ::google::protobuf::Descriptor* TActCustomGiftGetGiftReq_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TActCustomGiftGetGiftReq_reflection_ = NULL;
const ::google::protobuf::Descriptor* TActCustomGiftNotify_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TActCustomGiftNotify_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_net_2fActCustomGift_2eproto() {
  protobuf_AddDesc_net_2fActCustomGift_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "net/ActCustomGift.proto");
  GOOGLE_CHECK(file != NULL);
  TActCustomGiftInfo_descriptor_ = file->message_type(0);
  static const int TActCustomGiftInfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftInfo, giftid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftInfo, giftbuycount_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftInfo, giftgetcount_),
  };
  TActCustomGiftInfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TActCustomGiftInfo_descriptor_,
      TActCustomGiftInfo::default_instance_,
      TActCustomGiftInfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftInfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftInfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TActCustomGiftInfo));
  TActCustomGiftGetInfoArrRsp_descriptor_ = file->message_type(1);
  static const int TActCustomGiftGetInfoArrRsp_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftGetInfoArrRsp, arrgiftinfo_),
  };
  TActCustomGiftGetInfoArrRsp_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TActCustomGiftGetInfoArrRsp_descriptor_,
      TActCustomGiftGetInfoArrRsp::default_instance_,
      TActCustomGiftGetInfoArrRsp_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftGetInfoArrRsp, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftGetInfoArrRsp, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TActCustomGiftGetInfoArrRsp));
  TActCustomGiftGetGiftReq_descriptor_ = file->message_type(2);
  static const int TActCustomGiftGetGiftReq_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftGetGiftReq, giftid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftGetGiftReq, rewardindexarr_),
  };
  TActCustomGiftGetGiftReq_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TActCustomGiftGetGiftReq_descriptor_,
      TActCustomGiftGetGiftReq::default_instance_,
      TActCustomGiftGetGiftReq_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftGetGiftReq, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftGetGiftReq, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TActCustomGiftGetGiftReq));
  TActCustomGiftNotify_descriptor_ = file->message_type(3);
  static const int TActCustomGiftNotify_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftNotify, arrgiftinfo_),
  };
  TActCustomGiftNotify_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TActCustomGiftNotify_descriptor_,
      TActCustomGiftNotify::default_instance_,
      TActCustomGiftNotify_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftNotify, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TActCustomGiftNotify, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(TActCustomGiftNotify));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_net_2fActCustomGift_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TActCustomGiftInfo_descriptor_, &TActCustomGiftInfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TActCustomGiftGetInfoArrRsp_descriptor_, &TActCustomGiftGetInfoArrRsp::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TActCustomGiftGetGiftReq_descriptor_, &TActCustomGiftGetGiftReq::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TActCustomGiftNotify_descriptor_, &TActCustomGiftNotify::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_net_2fActCustomGift_2eproto() {
  delete TActCustomGiftInfo::default_instance_;
  delete TActCustomGiftInfo_reflection_;
  delete TActCustomGiftGetInfoArrRsp::default_instance_;
  delete TActCustomGiftGetInfoArrRsp_reflection_;
  delete TActCustomGiftGetGiftReq::default_instance_;
  delete TActCustomGiftGetGiftReq_reflection_;
  delete TActCustomGiftNotify::default_instance_;
  delete TActCustomGiftNotify_reflection_;
}

void protobuf_AddDesc_net_2fActCustomGift_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\027net/ActCustomGift.proto\022\002pb\"P\n\022TActCus"
    "tomGiftInfo\022\016\n\006GiftId\030\001 \001(\r\022\024\n\014GiftBuyCo"
    "unt\030\002 \001(\r\022\024\n\014GiftGetCount\030\003 \001(\r\"J\n\033TActC"
    "ustomGiftGetInfoArrRsp\022+\n\013ArrGiftInfo\030\001 "
    "\003(\0132\026.pb.TActCustomGiftInfo\"B\n\030TActCusto"
    "mGiftGetGiftReq\022\016\n\006GiftId\030\001 \001(\r\022\026\n\016Rewar"
    "dIndexArr\030\002 \003(\r\"C\n\024TActCustomGiftNotify\022"
    "+\n\013ArrGiftInfo\030\001 \003(\0132\026.pb.TActCustomGift"
    "Info", 324);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "net/ActCustomGift.proto", &protobuf_RegisterTypes);
  TActCustomGiftInfo::default_instance_ = new TActCustomGiftInfo();
  TActCustomGiftGetInfoArrRsp::default_instance_ = new TActCustomGiftGetInfoArrRsp();
  TActCustomGiftGetGiftReq::default_instance_ = new TActCustomGiftGetGiftReq();
  TActCustomGiftNotify::default_instance_ = new TActCustomGiftNotify();
  TActCustomGiftInfo::default_instance_->InitAsDefaultInstance();
  TActCustomGiftGetInfoArrRsp::default_instance_->InitAsDefaultInstance();
  TActCustomGiftGetGiftReq::default_instance_->InitAsDefaultInstance();
  TActCustomGiftNotify::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_net_2fActCustomGift_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_net_2fActCustomGift_2eproto {
  StaticDescriptorInitializer_net_2fActCustomGift_2eproto() {
    protobuf_AddDesc_net_2fActCustomGift_2eproto();
  }
} static_descriptor_initializer_net_2fActCustomGift_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int TActCustomGiftInfo::kGiftIdFieldNumber;
const int TActCustomGiftInfo::kGiftBuyCountFieldNumber;
const int TActCustomGiftInfo::kGiftGetCountFieldNumber;
#endif  // !_MSC_VER

TActCustomGiftInfo::TActCustomGiftInfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.TActCustomGiftInfo)
}

void TActCustomGiftInfo::InitAsDefaultInstance() {
}

TActCustomGiftInfo::TActCustomGiftInfo(const TActCustomGiftInfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.TActCustomGiftInfo)
}

void TActCustomGiftInfo::SharedCtor() {
  _cached_size_ = 0;
  giftid_ = 0u;
  giftbuycount_ = 0u;
  giftgetcount_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TActCustomGiftInfo::~TActCustomGiftInfo() {
  // @@protoc_insertion_point(destructor:pb.TActCustomGiftInfo)
  SharedDtor();
}

void TActCustomGiftInfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TActCustomGiftInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TActCustomGiftInfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TActCustomGiftInfo_descriptor_;
}

const TActCustomGiftInfo& TActCustomGiftInfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_net_2fActCustomGift_2eproto();
  return *default_instance_;
}

TActCustomGiftInfo* TActCustomGiftInfo::default_instance_ = NULL;

TActCustomGiftInfo* TActCustomGiftInfo::New() const {
  return new TActCustomGiftInfo;
}

void TActCustomGiftInfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<TActCustomGiftInfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(giftid_, giftgetcount_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TActCustomGiftInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.TActCustomGiftInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 GiftId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &giftid_)));
          set_has_giftid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_GiftBuyCount;
        break;
      }

      // optional uint32 GiftBuyCount = 2;
      case 2: {
        if (tag == 16) {
         parse_GiftBuyCount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &giftbuycount_)));
          set_has_giftbuycount();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_GiftGetCount;
        break;
      }

      // optional uint32 GiftGetCount = 3;
      case 3: {
        if (tag == 24) {
         parse_GiftGetCount:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &giftgetcount_)));
          set_has_giftgetcount();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.TActCustomGiftInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.TActCustomGiftInfo)
  return false;
#undef DO_
}

void TActCustomGiftInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.TActCustomGiftInfo)
  // optional uint32 GiftId = 1;
  if (has_giftid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->giftid(), output);
  }

  // optional uint32 GiftBuyCount = 2;
  if (has_giftbuycount()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->giftbuycount(), output);
  }

  // optional uint32 GiftGetCount = 3;
  if (has_giftgetcount()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->giftgetcount(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.TActCustomGiftInfo)
}

::google::protobuf::uint8* TActCustomGiftInfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.TActCustomGiftInfo)
  // optional uint32 GiftId = 1;
  if (has_giftid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->giftid(), target);
  }

  // optional uint32 GiftBuyCount = 2;
  if (has_giftbuycount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->giftbuycount(), target);
  }

  // optional uint32 GiftGetCount = 3;
  if (has_giftgetcount()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->giftgetcount(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.TActCustomGiftInfo)
  return target;
}

int TActCustomGiftInfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 GiftId = 1;
    if (has_giftid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->giftid());
    }

    // optional uint32 GiftBuyCount = 2;
    if (has_giftbuycount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->giftbuycount());
    }

    // optional uint32 GiftGetCount = 3;
    if (has_giftgetcount()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->giftgetcount());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TActCustomGiftInfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TActCustomGiftInfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TActCustomGiftInfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TActCustomGiftInfo::MergeFrom(const TActCustomGiftInfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_giftid()) {
      set_giftid(from.giftid());
    }
    if (from.has_giftbuycount()) {
      set_giftbuycount(from.giftbuycount());
    }
    if (from.has_giftgetcount()) {
      set_giftgetcount(from.giftgetcount());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TActCustomGiftInfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TActCustomGiftInfo::CopyFrom(const TActCustomGiftInfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TActCustomGiftInfo::IsInitialized() const {

  return true;
}

void TActCustomGiftInfo::Swap(TActCustomGiftInfo* other) {
  if (other != this) {
    std::swap(giftid_, other->giftid_);
    std::swap(giftbuycount_, other->giftbuycount_);
    std::swap(giftgetcount_, other->giftgetcount_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TActCustomGiftInfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TActCustomGiftInfo_descriptor_;
  metadata.reflection = TActCustomGiftInfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TActCustomGiftGetInfoArrRsp::kArrGiftInfoFieldNumber;
#endif  // !_MSC_VER

TActCustomGiftGetInfoArrRsp::TActCustomGiftGetInfoArrRsp()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.TActCustomGiftGetInfoArrRsp)
}

void TActCustomGiftGetInfoArrRsp::InitAsDefaultInstance() {
}

TActCustomGiftGetInfoArrRsp::TActCustomGiftGetInfoArrRsp(const TActCustomGiftGetInfoArrRsp& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.TActCustomGiftGetInfoArrRsp)
}

void TActCustomGiftGetInfoArrRsp::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TActCustomGiftGetInfoArrRsp::~TActCustomGiftGetInfoArrRsp() {
  // @@protoc_insertion_point(destructor:pb.TActCustomGiftGetInfoArrRsp)
  SharedDtor();
}

void TActCustomGiftGetInfoArrRsp::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TActCustomGiftGetInfoArrRsp::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TActCustomGiftGetInfoArrRsp::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TActCustomGiftGetInfoArrRsp_descriptor_;
}

const TActCustomGiftGetInfoArrRsp& TActCustomGiftGetInfoArrRsp::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_net_2fActCustomGift_2eproto();
  return *default_instance_;
}

TActCustomGiftGetInfoArrRsp* TActCustomGiftGetInfoArrRsp::default_instance_ = NULL;

TActCustomGiftGetInfoArrRsp* TActCustomGiftGetInfoArrRsp::New() const {
  return new TActCustomGiftGetInfoArrRsp;
}

void TActCustomGiftGetInfoArrRsp::Clear() {
  arrgiftinfo_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TActCustomGiftGetInfoArrRsp::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.TActCustomGiftGetInfoArrRsp)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
      case 1: {
        if (tag == 10) {
         parse_ArrGiftInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_arrgiftinfo()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_ArrGiftInfo;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.TActCustomGiftGetInfoArrRsp)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.TActCustomGiftGetInfoArrRsp)
  return false;
#undef DO_
}

void TActCustomGiftGetInfoArrRsp::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.TActCustomGiftGetInfoArrRsp)
  // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
  for (int i = 0; i < this->arrgiftinfo_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->arrgiftinfo(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.TActCustomGiftGetInfoArrRsp)
}

::google::protobuf::uint8* TActCustomGiftGetInfoArrRsp::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.TActCustomGiftGetInfoArrRsp)
  // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
  for (int i = 0; i < this->arrgiftinfo_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->arrgiftinfo(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.TActCustomGiftGetInfoArrRsp)
  return target;
}

int TActCustomGiftGetInfoArrRsp::ByteSize() const {
  int total_size = 0;

  // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
  total_size += 1 * this->arrgiftinfo_size();
  for (int i = 0; i < this->arrgiftinfo_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->arrgiftinfo(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TActCustomGiftGetInfoArrRsp::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TActCustomGiftGetInfoArrRsp* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TActCustomGiftGetInfoArrRsp*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TActCustomGiftGetInfoArrRsp::MergeFrom(const TActCustomGiftGetInfoArrRsp& from) {
  GOOGLE_CHECK_NE(&from, this);
  arrgiftinfo_.MergeFrom(from.arrgiftinfo_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TActCustomGiftGetInfoArrRsp::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TActCustomGiftGetInfoArrRsp::CopyFrom(const TActCustomGiftGetInfoArrRsp& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TActCustomGiftGetInfoArrRsp::IsInitialized() const {

  return true;
}

void TActCustomGiftGetInfoArrRsp::Swap(TActCustomGiftGetInfoArrRsp* other) {
  if (other != this) {
    arrgiftinfo_.Swap(&other->arrgiftinfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TActCustomGiftGetInfoArrRsp::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TActCustomGiftGetInfoArrRsp_descriptor_;
  metadata.reflection = TActCustomGiftGetInfoArrRsp_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TActCustomGiftGetGiftReq::kGiftIdFieldNumber;
const int TActCustomGiftGetGiftReq::kRewardIndexArrFieldNumber;
#endif  // !_MSC_VER

TActCustomGiftGetGiftReq::TActCustomGiftGetGiftReq()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.TActCustomGiftGetGiftReq)
}

void TActCustomGiftGetGiftReq::InitAsDefaultInstance() {
}

TActCustomGiftGetGiftReq::TActCustomGiftGetGiftReq(const TActCustomGiftGetGiftReq& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.TActCustomGiftGetGiftReq)
}

void TActCustomGiftGetGiftReq::SharedCtor() {
  _cached_size_ = 0;
  giftid_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TActCustomGiftGetGiftReq::~TActCustomGiftGetGiftReq() {
  // @@protoc_insertion_point(destructor:pb.TActCustomGiftGetGiftReq)
  SharedDtor();
}

void TActCustomGiftGetGiftReq::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TActCustomGiftGetGiftReq::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TActCustomGiftGetGiftReq::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TActCustomGiftGetGiftReq_descriptor_;
}

const TActCustomGiftGetGiftReq& TActCustomGiftGetGiftReq::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_net_2fActCustomGift_2eproto();
  return *default_instance_;
}

TActCustomGiftGetGiftReq* TActCustomGiftGetGiftReq::default_instance_ = NULL;

TActCustomGiftGetGiftReq* TActCustomGiftGetGiftReq::New() const {
  return new TActCustomGiftGetGiftReq;
}

void TActCustomGiftGetGiftReq::Clear() {
  giftid_ = 0u;
  rewardindexarr_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TActCustomGiftGetGiftReq::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.TActCustomGiftGetGiftReq)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 GiftId = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &giftid_)));
          set_has_giftid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_RewardIndexArr;
        break;
      }

      // repeated uint32 RewardIndexArr = 2;
      case 2: {
        if (tag == 16) {
         parse_RewardIndexArr:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 1, 16, input, this->mutable_rewardindexarr())));
        } else if (tag == 18) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, this->mutable_rewardindexarr())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_RewardIndexArr;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.TActCustomGiftGetGiftReq)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.TActCustomGiftGetGiftReq)
  return false;
#undef DO_
}

void TActCustomGiftGetGiftReq::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.TActCustomGiftGetGiftReq)
  // optional uint32 GiftId = 1;
  if (has_giftid()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->giftid(), output);
  }

  // repeated uint32 RewardIndexArr = 2;
  for (int i = 0; i < this->rewardindexarr_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(
      2, this->rewardindexarr(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.TActCustomGiftGetGiftReq)
}

::google::protobuf::uint8* TActCustomGiftGetGiftReq::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.TActCustomGiftGetGiftReq)
  // optional uint32 GiftId = 1;
  if (has_giftid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->giftid(), target);
  }

  // repeated uint32 RewardIndexArr = 2;
  for (int i = 0; i < this->rewardindexarr_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteUInt32ToArray(2, this->rewardindexarr(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.TActCustomGiftGetGiftReq)
  return target;
}

int TActCustomGiftGetGiftReq::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional uint32 GiftId = 1;
    if (has_giftid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->giftid());
    }

  }
  // repeated uint32 RewardIndexArr = 2;
  {
    int data_size = 0;
    for (int i = 0; i < this->rewardindexarr_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        UInt32Size(this->rewardindexarr(i));
    }
    total_size += 1 * this->rewardindexarr_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TActCustomGiftGetGiftReq::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TActCustomGiftGetGiftReq* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TActCustomGiftGetGiftReq*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TActCustomGiftGetGiftReq::MergeFrom(const TActCustomGiftGetGiftReq& from) {
  GOOGLE_CHECK_NE(&from, this);
  rewardindexarr_.MergeFrom(from.rewardindexarr_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_giftid()) {
      set_giftid(from.giftid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TActCustomGiftGetGiftReq::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TActCustomGiftGetGiftReq::CopyFrom(const TActCustomGiftGetGiftReq& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TActCustomGiftGetGiftReq::IsInitialized() const {

  return true;
}

void TActCustomGiftGetGiftReq::Swap(TActCustomGiftGetGiftReq* other) {
  if (other != this) {
    std::swap(giftid_, other->giftid_);
    rewardindexarr_.Swap(&other->rewardindexarr_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TActCustomGiftGetGiftReq::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TActCustomGiftGetGiftReq_descriptor_;
  metadata.reflection = TActCustomGiftGetGiftReq_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int TActCustomGiftNotify::kArrGiftInfoFieldNumber;
#endif  // !_MSC_VER

TActCustomGiftNotify::TActCustomGiftNotify()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:pb.TActCustomGiftNotify)
}

void TActCustomGiftNotify::InitAsDefaultInstance() {
}

TActCustomGiftNotify::TActCustomGiftNotify(const TActCustomGiftNotify& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:pb.TActCustomGiftNotify)
}

void TActCustomGiftNotify::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

TActCustomGiftNotify::~TActCustomGiftNotify() {
  // @@protoc_insertion_point(destructor:pb.TActCustomGiftNotify)
  SharedDtor();
}

void TActCustomGiftNotify::SharedDtor() {
  if (this != default_instance_) {
  }
}

void TActCustomGiftNotify::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* TActCustomGiftNotify::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return TActCustomGiftNotify_descriptor_;
}

const TActCustomGiftNotify& TActCustomGiftNotify::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_net_2fActCustomGift_2eproto();
  return *default_instance_;
}

TActCustomGiftNotify* TActCustomGiftNotify::default_instance_ = NULL;

TActCustomGiftNotify* TActCustomGiftNotify::New() const {
  return new TActCustomGiftNotify;
}

void TActCustomGiftNotify::Clear() {
  arrgiftinfo_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool TActCustomGiftNotify::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:pb.TActCustomGiftNotify)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
      case 1: {
        if (tag == 10) {
         parse_ArrGiftInfo:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_arrgiftinfo()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_ArrGiftInfo;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pb.TActCustomGiftNotify)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pb.TActCustomGiftNotify)
  return false;
#undef DO_
}

void TActCustomGiftNotify::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pb.TActCustomGiftNotify)
  // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
  for (int i = 0; i < this->arrgiftinfo_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->arrgiftinfo(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:pb.TActCustomGiftNotify)
}

::google::protobuf::uint8* TActCustomGiftNotify::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb.TActCustomGiftNotify)
  // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
  for (int i = 0; i < this->arrgiftinfo_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->arrgiftinfo(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb.TActCustomGiftNotify)
  return target;
}

int TActCustomGiftNotify::ByteSize() const {
  int total_size = 0;

  // repeated .pb.TActCustomGiftInfo ArrGiftInfo = 1;
  total_size += 1 * this->arrgiftinfo_size();
  for (int i = 0; i < this->arrgiftinfo_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->arrgiftinfo(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void TActCustomGiftNotify::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const TActCustomGiftNotify* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const TActCustomGiftNotify*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void TActCustomGiftNotify::MergeFrom(const TActCustomGiftNotify& from) {
  GOOGLE_CHECK_NE(&from, this);
  arrgiftinfo_.MergeFrom(from.arrgiftinfo_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void TActCustomGiftNotify::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void TActCustomGiftNotify::CopyFrom(const TActCustomGiftNotify& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TActCustomGiftNotify::IsInitialized() const {

  return true;
}

void TActCustomGiftNotify::Swap(TActCustomGiftNotify* other) {
  if (other != this) {
    arrgiftinfo_.Swap(&other->arrgiftinfo_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata TActCustomGiftNotify::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = TActCustomGiftNotify_descriptor_;
  metadata.reflection = TActCustomGiftNotify_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)
